"""Shared build-time machinery for all recipe generators.

Every generator uses the same two-stage (or three-stage) construction:
Chebyshev-Gauss nodes, a plain DCT to coefficients, a parameter-direction
fit per coefficient, and a writer that emits the baked table as a diffable
python module. All fit arithmetic stays in mpmath (the M1 floor rule:
rounding between stages puts eps-level sample noise under later fits).

Table axis convention, written into every emitted header: for a 2-D table,
TABLE[k, j] is the j-th parameter-direction coefficient of the k-th
argument-direction coefficient; parameters map affinely onto [-1, 1] from
the domain recorded in META. Emission is deterministic (repr of python
floats round-trips; no timestamps), so identical inputs give identical
bytes regardless of numpy version.
"""

import numpy as np

DPS = 40  # mpmath working precision for every generator


def nodes(mp, n):
    """First-kind Chebyshev points, the sampling nodes of every fit."""
    return [mp.cos(mp.pi * (2 * i + 1) / (2 * n)) for i in range(n)]


def dct(mp, samples):
    """Plain Chebyshev coefficients from samples at nodes(mp, len(samples))."""
    n = len(samples)
    c = []
    for j in range(n):
        s = mp.fsum(samples[i] * mp.cos(mp.pi * j * (2 * i + 1) / (2 * n)) for i in range(n))
        c.append(2 * s / n)
    c[0] /= 2
    return c


def param_fit(mp, rows):
    """Second stage: fit each coefficient across the parameter nodes, in mp."""
    nc = len(rows[0])
    return [dct(mp, [rows[i][k] for i in range(len(rows))]) for k in range(nc)]


def to_f64(rows):
    return np.array([[float(x) for x in row] for row in rows])


def _fmt_array(name, arr):
    arr = np.asarray(arr)
    lines = []
    if arr.ndim == 1:
        lines.append(f"{name} = np.array([")
        for i in range(0, arr.size, 4):
            lines.append("    " + ", ".join(repr(float(v)) for v in arr[i:i + 4]) + ",")
        lines.append("])")
    elif arr.ndim == 2:
        lines.append(f"{name} = np.array([")
        for row in arr:
            lines.append("    [" + ", ".join(repr(float(v)) for v in row) + "],")
        lines.append("])")
    elif arr.ndim == 3:
        lines.append(f"{name} = np.array([")
        for block in arr:
            lines.append("  [")
            for row in block:
                lines.append("    [" + ", ".join(repr(float(v)) for v in row) + "],")
            lines.append("  ],")
        lines.append("])")
    else:
        raise ValueError(f"unsupported table rank {arr.ndim}")
    return lines


def write_table_module(path, generator_module, axis_note, meta, scalars, arrays):
    """Emit a baked table as a python module. Deterministic bytes."""
    import mpmath

    meta = dict(meta, dps=DPS, mpmath=mpmath.__version__)
    lines = [
        f'"""Baked table. Generated by {generator_module}; do not edit.',
        f"Regenerate with:  python -m {generator_module}",
        "",
        f"Axes: {axis_note}",
        '"""',
        "",
        "import numpy as np",
        "",
        f"META = {meta!r}",
    ]
    for k, v in scalars.items():
        lines.append(f"{k} = {v!r}")
    for name, arr in arrays.items():
        lines.append("")
        lines.extend(_fmt_array(name, arr))
    path.write_text("\n".join(lines) + "\n")
    shapes = ", ".join(f"{k} {np.asarray(v).shape}" for k, v in arrays.items())
    print(f"wrote {path.name}: {shapes}")
