"""Generator for the besseli log-tables. Build-time only; mpmath inside.

I_v is positive and non-oscillatory, so it takes K's log treatment with J's
factored form:

- Inner, z = x^2 in [0, 64]:
      Lh(v, z) = ln[ Gamma(v+1) (x/2)^(-v) I_v(x) ]
  the log of the entire part h_v(z) = 0F1(; v+1; z/4). The z-degree is set
  by the complex zeros of I_v (for v=0 the nearest sits at z = -j_{0,1}^2
  ~ -5.78, giving rho ~ 1.8 and measured degree ~64); one v-panel suffices,
  there is no Gamma-pole feature (measured v-degree 52).

- Tail, t = 8/x on (0, 1]:
      Lt(v, t) = ln[ sqrt(2 pi x) e^(-x) I_v(x) ]
  The recessive e^(-2x) component is largest at half-integer v (measured
  worst t-degree 39, at v = 0.5); still converges cleanly at 48 nodes.

Both stages stay in mpmath (the M1 floor rule). Regenerate with:

    python -m chebax._src.recipes.besseli_gen
"""

import numpy as np

from chebax._src.recipes.besselj_gen import DPS, VMAX, _dct, _nodes, _to_f64, _nu_fit

ZMAX_I = 64.0
XS_I = 8.0
NZ_I = 72
NV_I = 64
NT_I = 48
NVT_I = 32


def generate_inner_table():
    import mpmath as mp

    with mp.workdps(DPS):
        zmax = mp.mpf(ZMAX_I)

        def lh(v, z):
            x = mp.sqrt(z)
            return mp.log(mp.besseli(v, x)) - v * mp.log(x / 2) + mp.loggamma(v + 1)

        tz = _nodes(mp, NZ_I)
        rows = [_dct(mp, [lh(v, (t + 1) / 2 * zmax) for t in tz])
                for v in [(s + 1) / 2 * mp.mpf(VMAX) for s in _nodes(mp, NV_I)]]
        return _to_f64(_nu_fit(mp, rows))


def generate_tail_table():
    import mpmath as mp

    with mp.workdps(DPS):
        xs = mp.mpf(XS_I)

        def lt(v, t):
            x = xs / t
            return mp.log(mp.besseli(v, x)) - x + mp.log(mp.sqrt(2 * mp.pi * x))

        tt = _nodes(mp, NT_I)
        rows = [_dct(mp, [lt(v, (t + 1) / 2) for t in tt])
                for v in [(s + 1) / 2 * mp.mpf(VMAX) for s in _nodes(mp, NVT_I)]]
        return _to_f64(_nu_fit(mp, rows))


def main():
    import pathlib

    import mpmath

    from chebax._src.recipes.besselj_gen import _format_array

    inner = generate_inner_table()
    tail = generate_tail_table()
    lines = [
        '"""Baked besseli log-tables. Generated by chebax._src.recipes.besseli_gen;',
        'do not edit. Regenerate with:  python -m chebax._src.recipes.besseli_gen',
        '"""',
        "",
        "import numpy as np",
        "",
        f"META = {{'nz': {NZ_I}, 'nv': {NV_I}, 'nt_tail': {NT_I}, 'nv_tail': {NVT_I}, "
        f"'zmax': {ZMAX_I!r}, 'xs': {XS_I!r}, 'vmax': {VMAX!r}, "
        f"'dps': {DPS}, 'mpmath': {mpmath.__version__!r}}}",
        f"ZMAX = {ZMAX_I!r}",
        f"XS = {XS_I!r}",
        f"VMAX = {VMAX!r}",
        "",
    ] + _format_array("TABLE_IN", inner) + [""] + _format_array("TABLE_TAIL", tail)
    out = pathlib.Path(__file__).with_name("besseli_table.py")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out.name} (inner {inner.shape}, tail {tail.shape})")


if __name__ == "__main__":
    main()
