"""Generator for the besselj nu-table. Build-time only; imports mpmath inside.

The table is the construction measured in experiments/02: fit the degree-24
Chebyshev coefficients of g_v(z) = 0F1(; v+1; -z/4) on z in [0, 64] at 64
Chebyshev nodes in v over [0, 10], then fit each coefficient as a Chebyshev
series in v. BOTH stages stay in mpmath and round to float64 only at the end:
rounding between the stages would put eps-level sample noise under the second
fit, and differentiation along v would amplify it by ~deg_v^2 (the M1 floor).

Regenerate with:  python -m chebax._src.recipes.besselj_gen
The output must reproduce the checked-in table bit for bit (tested).
"""

import numpy as np

NZ = 25      # z-degree 24, covers the worst case (v=0) with margin
NV = 64      # v-nodes
ZMAX = 64.0  # z = x^2, x in [0, 8]
VMAX = 10.0
DPS = 40


def generate_table():
    import mpmath as mp

    with mp.workdps(DPS):
        zmax = mp.mpf(ZMAX)
        vmax = mp.mpf(VMAX)

        def dct(samples):
            n = len(samples)
            c = []
            for j in range(n):
                s = mp.fsum(samples[i] * mp.cos(mp.pi * j * (2 * i + 1) / (2 * n))
                            for i in range(n))
                c.append(2 * s / n)
            c[0] /= 2
            return c

        tz = [mp.cos(mp.pi * (2 * i + 1) / (2 * NZ)) for i in range(NZ)]
        vnodes = [(mp.cos(mp.pi * (2 * i + 1) / (2 * NV)) + 1) / 2 * vmax for i in range(NV)]
        rows = [dct([mp.hyp0f1(v + 1, -((t + 1) / 2 * zmax) / 4) for t in tz]) for v in vnodes]
        table = [dct([rows[i][k] for i in range(NV)]) for k in range(NZ)]
    return np.array([[float(x) for x in row] for row in table])


def main():
    import pathlib

    import mpmath

    table = generate_table()
    lines = [
        '"""Baked besselj nu-table. Generated by chebax._src.recipes.besselj_gen;',
        'do not edit. Regenerate with:  python -m chebax._src.recipes.besselj_gen',
        '"""',
        "",
        "import numpy as np",
        "",
        f"META = {{'nz': {NZ}, 'nv': {NV}, 'zmax': {ZMAX!r}, 'vmax': {VMAX!r}, "
        f"'dps': {DPS}, 'mpmath': {mpmath.__version__!r}}}",
        f"ZMAX = {ZMAX!r}",
        f"VMAX = {VMAX!r}",
        "",
        "TABLE = np.array([",
    ]
    for row in table:
        lines.append("    [" + ", ".join(repr(x) for x in row) + "],")
    lines.append("])")
    out = pathlib.Path(__file__).with_name("besselj_table.py")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({table.shape[0]}x{table.shape[1]})")


if __name__ == "__main__":
    main()
