"""Generator for the bessely tables. Build-time only; mpmath inside.

Y_v combines every hard case: singular at x = 0 with a v-dependent exponent,
sign-changing (so no log-tabulation), and defined through the J_{+-v}
connection formula that cancels catastrophically near integer v (the R6/S3
structure). The classical resolution (Temme) adapted to tables:

- Reduce to small order: mu = v - floor(v) in [0, 1). The floor (not round)
  decomposition matters: the (x/2)^mu scaling below only removes the
  singular branch when mu >= 0 — for negative mu the divergent piece of
  Y_mu goes like (x/2)^{+mu}, T_a blows up like (x/2)^{-2|mu|} (~1e3 at
  mu=-0.3), and that magnitude leaks ~1e-11 of noise into every
  mu-reconstruction (measured; the first cut of this generator had it).
  On [0, 1) the pair Y_mu, Y_{mu+1} is tabulated DIRECTLY (mpmath at 40 dps
  absorbs the connection-formula cancellation during generation; the tables
  never see a pole), then the runtime lifts to v with the upward recurrence
  Y_{k+1} = (2k/x) Y_k - Y_{k-1}, which amplifies the dominant solution
  (= Y itself) and is therefore stable; measured lift error from f64 base
  pairs is <= 4.3e-16 even at v ~ 10, x = 1e-3. The step count round(v) is
  fixed at instantiation, so the unrolled loop stays branchless.

- Scale out the singular growth: the tables hold
      T_a(mu, u) = (x/2)^mu     Y_mu(x)
      T_b(mu, u) = (x/2)^(mu+1) Y_{mu+1}(x)
  in u = ln x on [ln 1e-6, ln 8]: bounded O(10) quantities, smooth in both
  variables (Y_0's log divergence becomes a linear-in-u term). The u-degree
  (~93 measured, 112 nodes baked) is set by the oscillatory stretch
  x in [turning point, 8] compressed into the top of the log interval.

- Mid, x in [8, 30]: Y_v fitted directly in x (same reasoning as besselj's
  mid region). Tail, x > 30: NO new tables — besselj's P, Q give
  Y = sqrt(2/(pi x)) (sin(x) A - cos(x) B) with the same A, B constants.

Both fit stages stay in mpmath (the M1 floor rule). Regenerate with:

    python -m chebax._src.recipes.bessely_gen
"""

import numpy as np

from chebax._src.recipes.besselj_gen import DPS, VMAX, _dct, _nodes, _to_f64, _nu_fit

XMIN_Y = 1e-6
X0_Y = 5.0   # NOT 8: the upward lift is neutral-to-cancelling while k < x, and
             # at x=8 the accumulated cancellation cost 1.4e-10; at x=5 the
             # measured lift error is <= 3.9e-16 for every worst order.
X1_Y = 30.0
NU_Y = 96    # u-nodes (worst measured degree 82, T_b near mu=1)
NM_Y = 48    # mu-nodes on [0, 1] (worst measured 33; no panels needed)
NX_MID_Y = 68  # x-degree 60 measured at v=9.97 on [5, 30]
NV_MID_Y = 48


def generate_inner_tables():
    import mpmath as mp

    with mp.workdps(DPS):
        u0, u1 = mp.log(mp.mpf(f"{XMIN_Y:.0e}")), mp.log(mp.mpf(X0_Y))
        tu = _nodes(mp, NU_Y)
        munodes = [(t + 1) / 2 for t in _nodes(mp, NM_Y)]
        rows_a, rows_b = [], []
        for mu in munodes:
            sa, sb = [], []
            for t in tu:
                x = mp.exp(u0 + (t + 1) / 2 * (u1 - u0))
                sa.append((x / 2) ** mu * mp.bessely(mu, x))
                sb.append((x / 2) ** (mu + 1) * mp.bessely(mu + 1, x))
            rows_a.append(_dct(mp, sa))
            rows_b.append(_dct(mp, sb))
        return _to_f64(_nu_fit(mp, rows_a)), _to_f64(_nu_fit(mp, rows_b))


def generate_mid_table():
    import mpmath as mp

    with mp.workdps(DPS):
        x0, x1 = mp.mpf(X0_Y), mp.mpf(X1_Y)
        tx = _nodes(mp, NX_MID_Y)
        rows = [_dct(mp, [mp.bessely(v, (t + 1) / 2 * (x1 - x0) + x0) for t in tx])
                for v in [(s + 1) / 2 * mp.mpf(VMAX) for s in _nodes(mp, NV_MID_Y)]]
        return _to_f64(_nu_fit(mp, rows))


def main():
    import math
    import pathlib

    import mpmath

    from chebax._src.recipes.besselj_gen import _format_array

    ta, tb = generate_inner_tables()
    mid = generate_mid_table()
    lines = [
        '"""Baked bessely tables. Generated by chebax._src.recipes.bessely_gen;',
        'do not edit. Regenerate with:  python -m chebax._src.recipes.bessely_gen',
        '"""',
        "",
        "import numpy as np",
        "",
        f"META = {{'nu': {NU_Y}, 'nm': {NM_Y}, 'nx_mid': {NX_MID_Y}, 'nv_mid': {NV_MID_Y}, "
        f"'xmin': {XMIN_Y!r}, 'x0': {X0_Y!r}, 'x1': {X1_Y!r}, 'vmax': {VMAX!r}, "
        f"'dps': {DPS}, 'mpmath': {mpmath.__version__!r}}}",
        f"XMIN = {XMIN_Y!r}",
        f"X0 = {X0_Y!r}",
        f"X1 = {X1_Y!r}",
        f"VMAX = {VMAX!r}",
        f"U0 = {math.log(XMIN_Y)!r}",
        f"U1 = {math.log(X0_Y)!r}",
        "",
    ] + _format_array("TABLE_A", ta) + [""] \
      + _format_array("TABLE_B", tb) + [""] \
      + _format_array("TABLE_MID", mid)
    out = pathlib.Path(__file__).with_name("bessely_table.py")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out.name} (A {ta.shape}, B {tb.shape}, mid {mid.shape})")


if __name__ == "__main__":
    main()
