"""Generator for the dawsn/erfcx tables. Build-time only; mpmath inside.

Both are parameter-free, so these are plain 1-D fits — no order tables.

- dawsn: odd and entire, D(x) = x E(x^2) with E fitted on z in [0, 36]
  (degree 37 measured); tail x D(x) = G(t), t = (6/x)^2, degree 10. The
  seam sits at 6, not 4: the recessive e^{-x^2} component (~1e-7 at x=4)
  measurably slows the tail fit there, while e^{-36} is below f64.
- erfcx: positive and smooth, fitted directly on x in [0, 6] (degree 32);
  tail x erfcx(x) = H(t), degree 9. Negative x is a runtime reflection,
  erfcx(-x) = 2 e^{x^2} - erfcx(x), which correctly overflows past
  x ~ -26.6.

Regenerate with:  python -m chebax._src.recipes.erf_gen
"""

import numpy as np

from chebax._src.recipes.besselj_gen import DPS, _dct, _nodes

XS_E = 6.0
NZ_DAWSN = 44
NT_DAWSN = 16
NC_ERFCX = 40
NT_ERFCX = 16


def generate_tables():
    import mpmath as mp

    with mp.workdps(DPS):
        xs = mp.mpf(XS_E)
        zmax = xs * xs

        def dawsn(x):
            return mp.sqrt(mp.pi) / 2 * mp.exp(-x * x) * mp.erfi(x)

        def erfcx(x):
            return mp.erfc(x) * mp.exp(x * x)

        e = _dct(mp, [(lambda x: dawsn(x) / x)(mp.sqrt((t + 1) / 2 * zmax))
                      for t in _nodes(mp, NZ_DAWSN)])
        g = _dct(mp, [(lambda x: x * dawsn(x))(xs / mp.sqrt((t + 1) / 2))
                      for t in _nodes(mp, NT_DAWSN)])
        c = _dct(mp, [erfcx((t + 1) / 2 * xs) for t in _nodes(mp, NC_ERFCX)])
        h = _dct(mp, [(lambda x: x * erfcx(x))(xs / mp.sqrt((t + 1) / 2))
                      for t in _nodes(mp, NT_ERFCX)])
    tof = lambda row: np.array([float(v) for v in row])
    return tof(e), tof(g), tof(c), tof(h)


def main():
    import pathlib

    import mpmath

    e, g, c, h = generate_tables()

    def arr(name, v):
        body = "\n".join("    " + ", ".join(repr(x) for x in v[i:i + 4]) + ","
                         for i in range(0, len(v), 4))
        return f"{name} = np.array([\n{body}\n])"

    lines = [
        '"""Baked dawsn/erfcx tables. Generated by chebax._src.recipes.erf_gen;',
        'do not edit. Regenerate with:  python -m chebax._src.recipes.erf_gen',
        '"""',
        "",
        "import numpy as np",
        "",
        f"META = {{'nz_dawsn': {NZ_DAWSN}, 'nt_dawsn': {NT_DAWSN}, "
        f"'nc_erfcx': {NC_ERFCX}, 'nt_erfcx': {NT_ERFCX}, 'xs': {XS_E!r}, "
        f"'dps': {DPS}, 'mpmath': {mpmath.__version__!r}}}",
        f"XS = {XS_E!r}",
        "",
        arr("DAWSN_E", e), "", arr("DAWSN_G", g), "",
        arr("ERFCX_C", c), "", arr("ERFCX_H", h),
    ]
    out = pathlib.Path(__file__).with_name("erf_table.py")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out.name} ({len(e)}+{len(g)}+{len(c)}+{len(h)} coefficients)")


if __name__ == "__main__":
    main()
